force-app/main/default/objects/Activity_Listing__c/Activity_Listing__c.object-meta.xml
<CustomObject>
    <label>Activity Listing</label>
    <nameField>
        <label>Activity Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities Listing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Listing__c/fields/Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>Additional_Info__c</fullName>
    <label>Additional Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity_Listing__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Activity Description</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Activity_Listing__c/fields/Images__c.field-meta.xml
<CustomField>
    <fullName>Images__c</fullName>
    <label>Images</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Activity_Listing__c/fields/max_price__c.field-meta.xml
<CustomField>
    <fullName>max_price__c</fullName>
    <label>max price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Activity_Listing__c/fields/min_price__c.field-meta.xml
<CustomField>
    <fullName>min_price__c</fullName>
    <label>min price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Activity_Listing__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <label>Place</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Day__c/Day__c.object-meta.xml
<CustomObject>
    <label>Day</label>
    <nameField>
        <displayFormat>DY-{0000}</displayFormat>
        <label>Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Day__c/fields/Itinerary__c.field-meta.xml
<CustomField>
    <fullName>Itinerary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Itinerary</label>
    <referenceTo>Itinerary__c</referenceTo>
    <relationshipLabel>Days</relationshipLabel>
    <relationshipName>Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FlightListing__c/FlightListing__c.object-meta.xml
<CustomObject>
    <label>FlightListing</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FlightListing__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Flight</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Economy</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HotelListing__c/HotelListing__c.object-meta.xml
<CustomObject>
    <label>HotelListing</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Itinerary__c/Itinerary__c.object-meta.xml
<CustomObject>
    <label>Itinerary</label>
    <nameField>
        <displayFormat>ITN-{0000}</displayFormat>
        <label>Itinerary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Itinerary__c/fields/Image_ID__c.field-meta.xml
<CustomField>
    <fullName>Image_ID__c</fullName>
    <description>ID of the Image</description>
    <label>Image ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Image_Link__c.field-meta.xml
<CustomField>
    <fullName>Image_Link__c</fullName>
    <description>Link of Image</description>
    <label>Image Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <description>Activity Interest of the customer</description>
    <label>Interest</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Max_Price__c.field-meta.xml
<CustomField>
    <fullName>Max_Price__c</fullName>
    <description>Miximun Budget of the Customer</description>
    <label>Max Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Min_Price__c.field-meta.xml
<CustomField>
    <fullName>Min_Price__c</fullName>
    <description>Minimun Budget of the Customer.</description>
    <label>Min Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Itinerary_Listing__c/Itinerary_Listing__c.object-meta.xml
<CustomObject>
    <label>Itinerary Listing</label>
    <nameField>
        <label>Itinerary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itineraries Listing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Itinerary_Listing__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <description>Destination Point of the Customers</description>
    <label>Destination</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Itinerary_Listing__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <description>Details Of Itinerary.</description>
    <label>Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Itinerary_Listing__c/fields/Interest__c.field-meta.xml
<CustomField>
    <fullName>Interest__c</fullName>
    <description>Activity Interest of the customer</description>
    <label>Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Cultural</fullName>
            </value>
            <value>
                <fullName>Relaxation</fullName>
            </value>
            <value>
                <fullName>other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Itinerary_Listing__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>To determine itinerary</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Itinerary_Listing__c/fields/IsRequest__c.field-meta.xml
<CustomField>
    <fullName>IsRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsRequest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LineItem__c/LineItem__c.object-meta.xml
<CustomObject>
    <label>LineItem</label>
    <nameField>
        <displayFormat>DY-{0000}</displayFormat>
        <label>Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LineItem__c/fields/Activity_Listing__c.field-meta.xml
<CustomField>
    <fullName>Activity_Listing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Listing</label>
    <referenceTo>Activity_Listing__c</referenceTo>
    <relationshipLabel>Days</relationshipLabel>
    <relationshipName>Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LineItem__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>Instruction for the Day</description>
    <label>Additional Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LineItem__c/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <description>All Details of the DAY</description>
    <label>Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LineItem__c/fields/FlightListing__c.field-meta.xml
<CustomField>
    <fullName>FlightListing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FlightListing</label>
    <referenceTo>FlightListing__c</referenceTo>
    <relationshipLabel>Days</relationshipLabel>
    <relationshipName>Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LineItem__c/fields/HotelListing__c.field-meta.xml
<CustomField>
    <fullName>HotelListing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HotelListing</label>
    <referenceTo>HotelListing__c</referenceTo>
    <relationshipLabel>Days</relationshipLabel>
    <relationshipName>Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LineItem__c/fields/Itinerary__c.field-meta.xml
<CustomField>
    <fullName>Itinerary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Itinerary</label>
    <referenceTo>Itinerary_Listing__c</referenceTo>
    <relationshipName>Days</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LineItem__c/fields/Short_Title__c.field-meta.xml
<CustomField>
    <fullName>Short_Title__c</fullName>
    <label>Short Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/LineItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Stay</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ItineraryCmpHandlerTest.cls
@isTest
public with sharing class ItineraryCmpHandlerTest {
    @isTest
    public static void testGetItinerary() {
        // Create Itnerary Listing data 
        //Name, Destination__c, Is_Active__c, Min_Price__c, Details__c, Max_Price__c, Image_Link__c, Image_ID__c, Interest__c
        Itinerary_Listing__c itineraryList = new Itinerary_Listing__c();
        itineraryList.Name = 'Test Itinerary';
        itineraryList.Image_ID__c = 'test_image_url';
        itineraryList.Destination__c = 'Test Destination';
        itineraryList.Is_Active__c = true;
        itineraryList.Min_Price__c = 100;
        itineraryList.Max_Price__c = 500;
        itineraryList.Details__c = 'Test Details';
        itineraryList.Image_Link__c = 'test_image_link';
        itineraryList.IsRequest__c = false;
        insert itineraryList;
        // create activity listing data
        //Name, Description__c, Place__c, Images__c, Additional_Info__c FROM Activity_Listing__c
        Activity_Listing__c activityList = new Activity_Listing__c();
        activityList.Name = 'Test Activity';
        activityList.Description__c = 'Test Description';
        activityList.Place__c = 'Test Place';
        activityList.Additional_Info__c = 'Test Additional Info';
        insert activityList;
        
        // Create Line Item data
        // Name, Detail__c, Itinerary__c, Short_Title__c, Additional_Information__c, 
        // Day__c, Type__c, Sequence__c, HotelListing__c, FlightListing__c, Activity_Listing__c, 
        // Duration__c FROM LineItem__c
        LineItem__c lineItem = new LineItem__c();
        //lineItem.Name = 'Test Line Item';
        lineItem.Itinerary__c = itineraryList.Id;
        lineItem.Short_Title__c = 'Test Short Title';
        lineItem.Detail__c = 'Test Detail';
        lineItem.Additional_Information__c = 'Test Additional Information';
        lineItem.Day__c = 1;
        lineItem.Type__c = 'Stay';
        lineItem.Sequence__c = 1;
        lineItem.activity_Listing__c = activityList.Id;
        lineItem.Duration__c = 2;
        insert lineItem;
        // Content version data
        // Create Content Version data
        ContentVersion contentVersion = new ContentVersion();
        contentVersion.Title = 'Test Content Version';
        contentVersion.PathOnClient = 'Test Document.jpg';
        contentVersion.VersionData = Blob.valueOf('Test Content');
        contentVersion.ContentLocation = 'S';
        contentVersion.IsMajorVersion = true;
        insert contentVersion;
        // Query the Content version to get the ContentDocumentId
        contentVersion v= [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Title = 'Test Content Version' LIMIT 1];
        // Create Content Document Link data
        ContentDocumentLink contentDocumentLink = new ContentDocumentLink();
        contentDocumentLink.ContentDocumentId = v.ContentDocumentId;
        contentDocumentLink.LinkedEntityId = itineraryList.Id;
        contentDocumentLink.ShareType = 'V';
        contentDocumentLink.Visibility = 'AllUsers';
        insert contentDocumentLink;
        // Call the method
        Test.startTest();
        String result = ItineraryCmpHandler.getItinerary();
        Test.stopTest();
        // Verify the result
        System.assertNotEquals(null, result, 'The result should not be null');
        System.assertNotEquals('', result, 'The result should not be empty');
        // Verify the itinerary listing
        List<Itinerary_Listing__c> itineraryListResult = [SELECT Id, Name, Destination__c, Is_Active__c, Min_Price__c, 
                                                          Details__c, Max_Price__c, Image_Link__c, Image_ID__c, Interest__c 
                                                          FROM Itinerary_Listing__c WHERE Id = :itineraryList.Id];
        System.assertEquals(1, itineraryListResult.size(), 'There should be one itinerary listing');
        Itinerary_Listing__c itinerary = itineraryListResult[0];
        System.assertEquals('Test Itinerary', itinerary.Name, 'The itinerary name should match');
        System.assertEquals('Test Destination', itinerary.Destination__c, 'The itinerary destination should match');
        System.assertEquals(true, itinerary.Is_Active__c, 'The itinerary should be active');
        System.assertEquals(100, itinerary.Min_Price__c, 'The itinerary min price should match');
        System.assertEquals(500, itinerary.Max_Price__c, 'The itinerary max price should match');
        System.assertEquals('Test Details', itinerary.Details__c, 'The itinerary details should match');
        System.assertEquals('test_image_link', itinerary.Image_Link__c, 'The itinerary image link should match');   
        System.assertEquals('test_image_url', itinerary.Image_ID__c, 'The itinerary image ID should match');
        
    }    
    @isTest
    public static void testGetIcon() {
        // Test the getIcon method
        String iconName = 'Stay';
        String expectedIcon = 'standard:household';
        String actualIcon = ItineraryCmpHandler.getIcon(iconName);
        System.assertEquals(expectedIcon, actualIcon, 'The icon should match the expected value');
        
        iconName = 'Activity';
        expectedIcon = 'standard:sales_channel';
        actualIcon = ItineraryCmpHandler.getIcon(iconName);
        System.assertEquals(expectedIcon, actualIcon, 'The icon should match the expected value');

        iconName = 'Travel';
        expectedIcon = 'standard:work_order';
        actualIcon = ItineraryCmpHandler.getIcon(iconName);
        System.assertEquals(expectedIcon, actualIcon, 'The icon should match the expected value');
    }
}